### ISSUE TITLE
not able to complle 

### ISSUE THREAD

**Issue by simplyrahul1** [gsauthof/osjitter#1]
$ CXXFLAGS='-Wall -O3 -g' cmake .. -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_ENABLE_GTEST_TESTS=0 -GNinja
CMake Error at CMakeLists.txt:5 (add_subdirectory):
  The source directory

    /home/ec2-user/software/osjitter-master/benchmark

  does not contain a CMakeLists.txt file.

**Comment by gsauthof** [comment]
It looks like your ` benchmark`  subdirectory is empty because the submodule isn't initialized.

I just tested the steps under https://github.com/gsauthof/osjitter#how-to-build on a fresh clone of this repository.
And indeed the mentioned git submodule command is essential.

When I don't skip that command the build succeeds.
